AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-ts

  Sample SAM Template for sam-ts

Resources:
  RestApiFunc:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: mainFunc.handler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /sum
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - mainFunc.ts
